### ISSUE TITLE
investigate not recommended for planting date logic

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-seedcalc#118]
**What's wrong**
- during a meeting there was some concern about some crops not being accurately recommended 

**What done looks like**
- look at the logic and verify it's working properly based on the api response date

**Comment by YazidZidane** [comment]
The planting date is only checked for NECCC and it's checking whether the planting date in the first step is during the plant's Reliable Establishment period.

**Comment by mikahpinegar** [comment]
this is fixed now that it's taking into account both windows
