### ISSUE TITLE
add sqft / acres toggle to pie charts

### ISSUE THREAD

**Issue by mikahpinegar** [precision-sustainable-ag/dst-seedcalc#151]
**What's wrong**
- the user may want to see the pie charts in different units

**What done looks like**
- add a toggle below each pie chart so that the user can change the units
- make sure that they can be independently toggled and not one toggle controlling both of them. the user may want to see pounds of seed per acre and plants per sqft

**Comment by YazidZidane** [comment]
closed as new changes should be made in #159
