### ISSUE TITLE
Update to Mix Ratios page

### ISSUE THREAD

**Issue by YazidZidane** [precision-sustainable-ag/dst-seedcalc#169]
**What done looks like**
- Update page with new slider design.
- Change seeding rate unit to lbs per 1000 sqft.
- flip the background color for editable and uneditable textfields.
- Change step caption styles to make it different than accordion headers.
- Make disclaimer more visible.

**Where the changes need to be made**
- MixRatios

**Comment by mikahpinegar** [comment]
i think one issue should be to cleanup the units and capitalizations in the whole app
