### ISSUE TITLE
Update Review Mix graph

### ISSUE THREAD

**Issue by YazidZidane** [precision-sustainable-ag/dst-seedcalc#170]
**What's wrong**
- The graph in Review Mix is confusing

**What done looks like**
- Change the graph to a barchart with appropriate captions to each term.

**Where the changes need to be made**
- ReviewMix

**Comment by mikahpinegar** [comment]
- title: `Seeding rate impact from your decisions`
- Captions for each bar
- - Initial seeding rate
- - Mix proportion
- - Seeding method
- - Management
- - Bulk Germination and Purity
