### ISSUE TITLE
Modularize files

### ISSUE THREAD

**Issue by 0101kvmt** [precision-sustainable-ag/dst-seedcalc#78]
Break down files that are 700+ lines of code to either re-usable components or smaller files.
- [x]  Site Condition
- [x]  Species Selection
- [x]  Mix Ratios
- [x]  Mix Seeding Rate
- [x]  Seeding Method
- [x]  Seed Tag Info
- [x]  Review Mix
- [x]  Confirm Plan

**Comment by YazidZidane** [comment]
- [ ]  Site Condition
- [ ]  Species Selection
- [ ]  Mix Ratios
- [ ]  Mix Seeding Rate
- [ ]  Seeding Method
- [ ]  Seed Tag Info
- [ ]  Review Mix
- [ ]  Confirm Plan
