### ISSUE TITLE
Fix up Species Selection Image list

### ISSUE THREAD

**Issue by 0101kvmt** [precision-sustainable-ag/dst-seedcalc#94]
**Issue:**
Currently, depending on the size of the browser, the images of the seeds are constantly resizing themselves. 

![Image](https://github.com/precision-sustainable-ag/dst-seedcalc/assets/23531153/9be1bf11-9472-4e5d-8d80-14f8b12db14c)
![Image](https://github.com/precision-sustainable-ag/dst-seedcalc/assets/23531153/65dbcab6-805b-4bc4-973d-ea4efe823d70)

**Expectation:**
Images remain the same square ratio regardless of screen size.

**Comment by madhabpaul** [comment]
@0101kvmt I want to work on this issue. Can you assign me to this issue?
