### ISSUE TITLE
Add "<=" to the expect column in NRCS modal

### ISSUE THREAD

**Issue by 0101kvmt** [precision-sustainable-ag/dst-seedcalc#97]
In the NRCS Standards modal, we have an expect value but it doesn't specify whether the expectation should be "=" the value or "<=" the value.

![Image](https://github.com/precision-sustainable-ag/dst-seedcalc/assets/23531153/fd3abf39-e78d-44da-8716-ca2463f248ac)

Expectation:

Add a "<=" before the expect value

**Comment by mikahpinegar** [comment]
use the actual symbol instead of `<=`
